defaults:
  port.server: "60001"

cmd:
  - -batchmode
  - -nographics
  - -logFile
  - -port
  - ${port.server}

script:
  initialState: idle
  states:
    idle:
      events:
        - type: literal
          pattern: STATE_CHANGE_TO_PLAY
          ignoreCase: true
          nextState: playing
        - type: timer
          interval: 900000 # 1000 * 60 * 15 = 15 minutes
          nextState: end
    playing:
      events:
        - type: literal
          value: STATE_CHANGE_TO_END
          nextState: end
    end:
      events:
        - type: timer
          interval: 60000 # 60 seconds
          nextState: quit
  transitions:
    - to: idle
      command: |
        echo "Idle..."
    - to: playing
      command: |
        echo "Playing..."
    - to: end
      command: |
        echo "End..."
    - to: quit
      command: |
        echo "Quit..."